export const ROOT_KEYS = {
  me: "me",
  users: "users",
  branches: "branches",
  staff: "staff",
  attendance: "attendance",
  cleaning: "cleaning",
  inventory: "inventory",
  sheets: "inventory-sheets",
  masterProducts: "master-products",
  productRequests: "product-requests",
  customers: "customers",
  reviews: "reviews",
  complaints: "complaints",
  inspections: "inspections",
  specialRemarks: "special-remarks",
  adminDashboard: "admin-dashboard",
  managerDashboard: "manager-dashboard",
  reports: "reports",
  audit: "audit",
} as const;
